### ISSUE TITLE
Want some help?

### ISSUE THREAD

**Issue by webysther** [hanatos/vkdt#117]
I will link here the issue on ansel which link more issues in darktable: 

- aurelienpierreeng/ansel/issues/323
- darktable-org/darktable/issues/16252
- darktable-org/darktable/issues/16253
- darktable-org/darktable/issues/16255

**Comment by webysther** [comment]
The DAG execution can be made fully on cli?

**Comment by hanatos** [comment]
sorry i only very sparsely random sampled the link tree you posted above and i couldn't get a clear image of what exactly you're after. something remote desktop with even remoter storage.

in any case i'm going to say whatever parafin wrote in one of the issues above: i'm not an active darktable dev any more but worried about features that are not well thought out. i'm going to say this is the case here since i didn't understand exactly what would be the use case/workflow.

as to sqlite: vkdt does not use a database (bloatware) but parses a minimum set of human readable text files. the rest is folder/filesystem based and hence you could probably do random parallel processing from cli (like you would with imagemagick, say).

not sure i understand the question about DAG and cli. the graph is [defined in a .cfg file](https://github.com/hanatos/vkdt/blob/master/bin/examples/spheres.cfg) and that can be passed to the cli (or additional config source lines can be given on the command line). you could also concatenate cfg and preset files in bash to form valid cfg files for the cli.

as was already discussed in the threads linked above, there's probably a hardware limit to parallelism. you can manually distribute different cli invocations to different gpu, or if you're positive that rendering doesn't require the full device you can schedule multiple invocations to the same gpu.

**Comment by webysther** [comment]
> sorry i only very sparsely random sampled the link tree you posted above and i couldn't get a clear image of what exactly you're after. something remote desktop with even remoter storage.
> 
> in any case i'm going to say whatever parafin wrote in one of the issues above: i'm not an active darktable dev any more but worried about features that are not well thought out. i'm going to say this is the case here since i didn't understand exactly what would be the use case/workflow.
> 
> as to sqlite: vkdt does not use a database (bloatware) but parses a minimum set of human readable text files. the rest is folder/filesystem based and hence you could probably do random parallel processing from cli (like you would with imagemagick, say).
> 
> not sure i understand the question about DAG and cli. the graph is [defined in a .cfg file](https://github.com/hanatos/vkdt/blob/master/bin/examples/spheres.cfg) and that can be passed to the cli (or additional config source lines can be given on the command line). you could also concatenate cfg and preset files in bash to form valid cfg files for the cli.
> 
> as was already discussed in the threads linked above, there's probably a hardware limit to parallelism. you can manually distribute different cli invocations to different gpu, or if you're positive that rendering doesn't require the full device you can schedule multiple invocations to the same gpu.

Thanks you, this answer my question, BTW what is your workflow?
