### ISSUE TITLE
Core dump on qvk_create_swapchain()

### ISSUE THREAD

**Issue by MartijnBraam** [hanatos/vkdt#15]
I'm just checking out what vkdt does, tried to run it on my archlinux install after building it from source. It crashes with this error:

```
[gui] monitor [0] LGD 0x0540 at 0 0
[gui] monitor [1] DEL DELL U2515H at 1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_wayland_surface
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

vkdt: qvk/qvk.c:227: VkResult qvk_create_swapchain(): Assertion `qvk.num_swap_chain_images < QVK_MAX_SWAPCHAIN_IMAGES' failed.
[1]    144589 abort (core dumped)  ./vkdt
```

The GPU is Intel HD graphics 630, this is the output from vulkaninfo: https://paste.sr.ht/~martijnbraam/69129017397a1c30779823a01a60a6bb41763a05

**Comment by hanatos** [comment]
oh, great! looks like you're using wayland.. i've never tried this before, though glfw should support it. did you try to `make debug` and run `vkdt -d all` to see whether there are any useful vulkan validation layer warnings before it runs into the assertion?

**Comment by hanatos** [comment]
hm without further details i can't really say anything. your vulkaninfo output says it supports xorg surfaces (VK_KHR_xcb_surface
VK_KHR_xlib_surface), not wayland. this makes me assume you installed glfw in the wayland version instead of the xorg version (on debain `libglfw3-wayland` instead `libglfw3`). i'm going to claim that's the issue and will close this now. feel free to reopen with more details in case.

either way i unfortunately can't test wayland since i'm on an NVIDIA gpu.
