### ISSUE TITLE
running on amdgpu fails with: samplerYcbcrConversion must be enabled to call vkCreateSamplerYcbcrConversion.

### ISSUE THREAD

**Issue by edgecase14** [hanatos/vkdt#17]
I have enabled debug, Freetype and exiv2 when building ie `$ make debug -j8`

[debug.log](https://github.com/hanatos/vkdt/files/5894287/debug.log)
[vulkaninfo.txt](https://github.com/hanatos/vkdt/files/5894288/vulkaninfo.txt)

This problem goes away if built without debug, ie` $ touch qvk/qvk.c ; make -j8 ` 

Ubuntu 20.10, mesa 20.3.3 from PPA kisak APU 2400G with Vega56 GPU

**Comment by hanatos** [comment]
for the record: we discussed in irc and i think this may be an issue with the vulkan validation layers. the cbcr conversion features seem to be all correctly inited as far as i can tell, but the validation layers still complain in this setup (they don't on my machine: debian sid with xorg/nvidia 460.X drivers from experimental). until someone proves me wrong i'm going to claim this is not my bug and will recommend running in release mode `make` instead of `make debug`. closing for now, please reopen if more information pops up.
