### ISSUE TITLE
[features] local edits / nodes / multi-instanciation / pipe

### ISSUE THREAD

**Issue by aurelienpierre** [hanatos/vkdt#2]
Even if I know it can be a burden, I don't think we can avoid local edits and masking. If only for one reason, it would be because most softs don't blend in linear space as they should and don't make correct use of associated alpha blending.

Use cases involving local edits can be :

- outdoors HDR scenes : separating ground and sky, to perform selective luminance/exposure and WB corrections,
- indoors HDR scenes : separating windows/outdoors parts and indoors one, to do the same
- portrait/fashion/macro : separating subject from background for selective colour, sharpness, luminance adjustments

The way current dt is doing it is problematic though, because drawn masks are blended from the input/output of the current module, and the parametric blending depends on what is done earlier in the pipe. Set up a luminance parametric mask for color edits, change the exposure earlier, and your mask is lost. Also, masks need to be defined for each filter, possibly duplicated (even if the last raster mask option is nice).

Some filters make sense at a general level (colour input/output transforms, camera exposure compensation, denoising, LUTs, reconstructive deblurring), some make sense at a local level (healing/cloning/in-painting), some make sense at both (lumiance/colour adjustments, blurring/local contrast). For this reason, having reorderable and multi-instanciable filters is a necessity.

So, I think it should be better to have a first round of global edits on the raw file, for operations that make sense at the scene level (relighting, spectrum modification), at the camera level (white balance, exposure compensation, demosaic, colour profile, lens profile), and the signal processing/reconstruction (healing, inpainting). At this step, I think the use of masking/blending equals tempering bad filters that break, so it should not happen ideally.

Then, a mask manager would split the global image into zones, defined by drawn and/or parametric masks or by auto/assisted image segmentation. Each zone would be loaded with the required filters, upon request, and possibly processed in parallel.

After that, the zones are blended with a proper associated alpha, and go to the final step of global edits (HDR/filmic curves, gamut mapping, output colour profile, film emulation LUTs, possibly brushed dodging & burning, etc.).

![dt-pipe](https://user-images.githubusercontent.com/2779157/61438774-853ed780-a940-11e9-9dc3-9c7384f63bb9.png)

In this architecture, parallel zones are loaded with filters stacked in serie, in parallel, so we limit the dependency of masking parameters to the initial step of global edits, and we don't need to blend after every filter. I don't think parametric blending will be necessary at all for these filters (inside zones), if algos behave properly (just a regular opacity, maybe some blendings like multiply or average).

I don't believe in several pipes (preview/full-size) because some operations are not scale-invariant and the branching it involves makes a lot of trouble to maintain, regarding scaling of masks coordinates and such. I would just use 2 intermediate full-size raster caches, to store the image state before and after the zones splitting, and maybe a third right after the demosaicing and denoising step, because these can be heavy. Or maybe just abuse the RAM and cache every filter's output as long as there is still space (8 GB = 20 copies of a 24 Mpx image in RGBa single-precision float).

**Comment by hanatos** [comment]
hi,

thanks for the detailed thoughts. a few additional random thoughts here:

i agree on the use cases. i think most of these should be covered fairly well by parametric masks, and i agree it would be great to create these based on very early stages of the pipeline so they would be independent of artistic grading/tone mapping later on. this is not a problem in the backend now, we have a completely free node graph and can connect whatever we want.

i'm slightly worried about hand drawn masks, as the pipeline is currently a graph of compute shaders. i'll need to setup a graphics command buffer, too, to rasterise brush strokes. no big deal but is a larger architectural thing and i should start doing that soon to make sure we don't paint ourselves in a corner.

re: preview pipe: i had in mind to run a completely synchronous context pipeline to complement the ROI processing, which can be wired into a node as additional input. to tell the truth for now i've been too lazy to actually do it, because the edits are ridiculously fast (okay the pipelines are short, but it's still insane). on good hardware going forward in the next 10 years.. for 24MP i doubt you'd need to downsize/crop for processing at all. for larger res maybe, but maybe it's enough to just use faster half-size demosaic or moderate downsizing (which still means modules need to be scale aware and take care that the result is approximately independent of zoom).

the processing graph supports "caching". the memory allocator can just artificially increase the reference count of a VkImage you want to keep and consecutive runs will start the command buffer after this stage. this is what currently happens to avoid running through rawspeed repeatedly, and would have to be generalised just a slight bit.

re: ram: this is scarce on GPU, but we're in the several gigabyte range nowadays too. that said, i'm currently running in rgba32f and i think rgba16f should be good for pretty much all cases and a lot faster and more memory efficient, too.

**Comment by hanatos** [comment]
i think this discussion is now mostly outdated. there's the `draw` module which handles rasterised/hand drawn masks, and it can be incorporated into the node graph in completely free ways. the pipeline now runs mostly in rgba/f16 by default, and the memory allocator so far seems to do a good job. i'm not even doing any caching since reprocessing everything from scratch at full res is fast enough on mid-range hardware.
