### ISSUE TITLE
CC24 (pick node) reference values should be plotted in CIE diagram

### ISSUE THREAD

**Issue by edgecase14** [hanatos/vkdt#23]
the mouse-over on individual difference areas is hard to use while adjusting v4l2 camera settings such as white balance, saturation, etc., with another application, ie qv4l2, that requires mouse input.

**Comment by hanatos** [comment]
okay, thinking about it i don't want to route data on the gpu. i went the more manual way so the `ciediag` module will have reference parameters exactly like the `pick` module:

![screen](https://user-images.githubusercontent.com/1574185/137885560-ec90edb0-ce82-4797-b87f-d1e0fa438908.jpg)

the yellow spots mark the reference values. you can arrive at these settings by applying the following preset:

[cc24ref.txt](https://github.com/hanatos/vkdt/files/7372118/cc24ref.txt)

(rename to `~/.config/vkdt/presets/cc24ref.pst` and then press ctrl-p in darkroom mode and select this preset)

this is assuming you have a `pick:01` module as well as `ciediag:01`. i forget whether these rec2020 coordinates are for my specific colour checker or for the default one that comes with argyll.

i may want to make the yellow spots overlays rather than underlays to better show.

anyways, hope that helps, let me know.
