### ISSUE TITLE
Sliders effect applied too strongly

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#49]
Hello @hanatos,

When using any slider to edit pictures, i always get the feeling that the effect (exposure, shadows, ... all of them) is applied very strongly even with a very tiny bit of wheeling/scrolling.

Is that on purpose ?

I understand effects may actually be applied linearly but I always overshoot PP and must everytime resort to play a second time with the mouse at pixel level to get the expected amount of effect.

Could effects be applied less linearly but more exponentially, so that the user may apply subtle amount of effect without struggle.

Note: I use vkdt on JPEG ;-) if this is of value

Thanks a lot,
GLLM

**Comment by qosch** [comment]
I don't think there's anything wrong with the sliders. I can, however, understand this complaint for a few specific sliders:
- the denoise slider does almost nothing for me. I see a strong effect as soon as it is unequal zero but otherwise the "strength" slider has almost no effect and the "luma" slider has no effect at all. That is without adjusting the "noise a" and "noise b" sliders in the "i-raw" module. It might be different if those are set to reasonable levels for my camera/ISO level.
- when used to decrease contrast (values smaller 1), the "shadows" and "highlights" sliders in the "llap" module very quickly lead to unusable results. The usable range for some of my picures with very high dynamic range is 0.97-1.0. But again, this has nothing to do with the slider but with the module.

**Comment by hanatos** [comment]
* yes you definitely need to give good/correct noise a and noise b values, else the denoise module yields bad results.
* yes the llap parameters i'm not very sure about being final/perfect. maybe it makes sense to limit the range from below (you can always ctrl-click and type to extend), that is a good idea for a simple change.

**Comment by GLLM** [comment]
Thank you both for your comments !
I understand that you dont want to introduce distortion between the slider & the applied effect.

Indeed, darktable zoomable sliders are a suiting solution in dt.
Not sure you want to implement this here, or something similar.

I'll try using vkdt more and see if I get used to the amount of applied effect !
Thanks
GLLM

**Comment by hanatos** [comment]
okay, closing this until then. feel free to reopen if you develop a strong opinion on it or have a concrete suggestion.
