### ISSUE TITLE
Bug: delete imag's) does not reset when changing selection

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#62]
Test case:
* open a folder
* select a picture
* click on delete image(s) --> the confirmation button appears on its right
* change your mind, do not proceed with deletion
* switch to another file and select it

--> the deletion confirmation message is still there, as if it was on this 2nd file that I performed the click on 'delete images(s).

**Expectation:** the confirmation message disappears if the selection changes

Video of the issue

https://user-images.githubusercontent.com/3989573/208250890-e7329c52-ddce-4674-b24e-4fed5ad3f47d.mp4

Thanks
GLLM

**Comment by hanatos** [comment]
hm video doesn't show here, but i think i know what you mean. not sure i want to change this since it would require to expose the state of this button to other places in the code, or compute a hash for the selection or something. i relabeled the first/left button now to reflect that you can actually switch off the "sharp" mode again. would that be enough to handle expectations?

**Comment by GLLM** [comment]
Tested the new message.
I think it would do the job... would a modal be possible ? or you want to avoid this ?

One note: rather that clicking "no i do not " I pressed escape ... alas  :-D

**Comment by hanatos** [comment]
okay closing this for now. i don't particularly like modals. we have some now (tags, blocks, add module) but these are very quick to handle with the keyboard.
