### ISSUE TITLE
[FR] Node editor in a second screen

### ISSUE THREAD

**Issue by Yvan-56** [hanatos/vkdt#64]
Hi hanatos,
I have 2 monitors (maybe something not so unusual these days?), and so, it would be nice to be able to detach the node editor:
- the node editor on one monitor;
- the image on the second monitor.
Thank you,
Best regards,
Yvan

**Comment by hanatos** [comment]
hi, this sounds like a reasonable request. i suppose that would be realisable via the docking functionality in imgui, or using some custom layout in a super wide window. the vkdt window is colour managed across two screens only if it stays a single window. i currently don't have a dual monitor setup to test but other than that i don't think this should be much work. also since the image is always processed in full anyways it shouldn't have any speed impact.

**Comment by cherob67** [comment]
I think it's a very goof idea to have two separate windows, one for the node configuration and the adjustement and another for the image. It should be very fine to be able to do adjustement in the node editor. 
Otherwise, is it possible to add one or several display on the right of the windows like  this ?
![wkdt](https://user-images.githubusercontent.com/46007178/211150836-da4d83e6-8824-402e-b0f1-2086a7592ec7.jpg)

**Comment by hanatos** [comment]
the special display instance names are `hist` (the top one that usually has the histogram), `main` (goes into large center in darkroom mode) and `view0` (also shows in dr mode) as well as `view1` which only shows in node editor view.

about the second screen: i'd have to redo some of the colour management for a second window, so i'd rather not. it would be relatively easy to have the single window span both monitors and show the large image on one of the two.

**Comment by cherob67** [comment]
Thanks for your answer. About second screen, it should be best to have two windows and only one with colour management (the main).

**Comment by hanatos** [comment]
just a quick heads-up. second screen doesn't require docking, just viewport support in imgui. that kinda works, i can drag windows around and place them on a second screen (in a test branch), but is super clumsy. will probably have to introduce some imgui functionality that just opens the next window fullscreen on the other monitor.

will see about colour management, would absolutely hate to lose it/not ship without.

**Comment by hanatos** [comment]
as of ce68d2f7489ebe0397ab045c63a9f1565cde76a8, you can now press the `dual monitors` button in the `settings` expander in the node editor view. it will pop out the main display image in a separate window which you can place on your secondary screen, resize to your needs, and zoom and pan around in.

both main and popped out windows are colour managed for the screens they are displayed on (and correctly managed in both halves if they partially overlap). that requires two correct `display.<output>` files of course.

remember to do `git submodule update -f` because it requires a new version of imgui (viewport/docking branch). the change was a bit delicate, so i might have broken something that i'm not aware of (as you can tell by the git history, i did fix a fair amount of things). if so, let me know.

**Comment by cherob67** [comment]
Hello !

I have just recompile vkdt (without git - more simple for me) and I succeed using it ! I can see the effect on the picture of a module. It's great and fine and very promising ! 

thanks

Robert
![vkdt_2screen](https://user-images.githubusercontent.com/46007178/219783665-9497e207-731c-4285-9904-ea71aafc993b.jpg)

**Comment by cherob67** [comment]
I don't know if it is possible but i think it should very practice and useful to be able to access to the tweak of a selected module from the pipeline screen (something like that).
![vkdt_2screen_a](https://user-images.githubusercontent.com/46007178/219852611-3f9c11a4-3774-4a97-accb-ba605b752e9e.jpg)

**Comment by hanatos** [comment]
yes that makes a lot of sense and want to do this. i'll probably restructure a bit. remove the "pipeline config" tab in darkroom mode completely (mostly duplicates functionality of the node graph view), show the parameter ui for the selected nodes in the node editor, and perspectively also introduce a separate view for animation/keyframes.
