### ISSUE TITLE
Feature: noise profiles from Darktable

### ISSUE THREAD

**Issue by ghost** [hanatos/vkdt#77]
Maybe could be used In the `i-raw main` module to automatically adjust the values based on the camera and ISO

**Comment by hanatos** [comment]
the profiles are unfortunately incompatible because vkdt denoises pre demosaic pre blackpoint subtraction (such that negative values can be used to correctly infer a mean of zero for denoised blacks). it's probably possible to approximately convert the profiles, but the darktable ones inherently have lost some information.

that being said the profiling process got a lot more robust, more often than not i can generate good profiles from just any image (e.g. the one just edited). probably a better idea to introduce a quick button in the gui to generate a new profile on the fly.
